### ISSUE TITLE
Publish on PyPI (pip)

### ISSUE THREAD

**Issue by dnadlinger** [OxfordIonTrapGroup/atomic_physics#28]
With this being a standalone package with a refreshing lack of unwieldy dependencies, we should definitely publish this on PyPI, so we can tell people to just `pip install ion_phys`.

**Comment by cjbe** [comment]
+1, but instead "pip install atomic"

**Comment by dnadlinger** [comment]
That name's already taken, though. ;)

**Comment by hartytp** [comment]
@dnadlinger agreed! I'm happy to do this at some point, but I'd like it to get a bit more use first so we can work some of the quirks out.
