### ISSUE TITLE
Method to calculate absolute transition frequency

### ISSUE THREAD

**Issue by cjbe** [OxfordIonTrapGroup/atomic_physics#29]
It would be useful to have a method that calculates the absolute transition frequency between any pair of states

**Comment by hartytp** [comment]
Out of curiosity, what's the use-case? Does the splitting of the magnetic/hyperfine subleves make a noticeable difference to the overall transition frequency?

Anyway, yes, that's a good idea. I don't like the `ion.delta` method. Maybe the way to go here is to have a method like `ion.transition_frequency(lower_state, upper_state, absolute=True)` (bikeshed names and default values) to replace the `delta` method.

**Comment by cjbe** [comment]
Well, this way a Stark shift solver can just sum over all levels, and one does not have to think (all levels being S-P1/2, S-P3/2, or D-P1/2, D-P3/2).

Similarly, a Raman matrix element calculation can just sum over all coupled levels, rather than require extra manual work, meaning it works for all ions and all wavelengths for free

**Comment by hartytp** [comment]
So you want to do something like this calculation, summing over transitions: https://github.com/OxfordIonTrapGroup/ion_phys/blob/8a4fc96e531332391a871617ed102166d9b5323b/ion_phys/rate_equations.py#L76-L77 ?

The way I like to write code is to keep things as matricies which I can multiple. AFAICT the way you're suggesting you'd be iterating over pairs of states (since I assume `get_frequency` or whatever would return a number)? Or would you want something that actually returns an absolute energy matrix?

**Comment by hartytp** [comment]
Following: https://github.com/OxfordIonTrapGroup/ion_phys/issues/27#issuecomment-663148969 I think the best bet here is:
- [ ] replace `delta` with `get_energy(ind, absolute=True)` and `get_frequency(lower, upper, absolute=True)` accessors.

**Comment by cjbe** [comment]
> So you want to do something like this calculation...

Yes, but in more complex situations, e.g. for a Raman coupling:
Omega = \sum_{all e} g1*g2*pol1(q1)*pol2(q2)*matrix_element(dn,e)*matrix_element(e,up) / (frequency(dn,up,e)-omega0)

**Comment by hartytp** [comment]
Ok. Are you happy with my proposed solution? If so, it's quick to implement so I'll aim to do it soon...

**Comment by cjbe** [comment]
Yes - LGTM
(nit pick: I feel a "relative" kwarg is better than "absolute", as it is not clear to me what the opposite of "absolute" is as an API user)

**Comment by hartytp** [comment]
@cjbe I think this is now resolved by https://github.com/OxfordIonTrapGroup/atomic_physics/blob/982cb6f2d62123b5d1941043655fda23e817aa13/atomic_physics/common.py#L260-L284

LMK if this doesn't resolve your issue
